# Site settings
title: Tu sorprendete título haha
email: final.africae@gmail.com
description: "Sitio personal donde escribiré mis artículos, probaré el sitio y escribiré de lo que lea, platique y experimente."
baseurl: ""
url: "http://pazthor.github.io"
twitter_username: Pazthor
github_username:  Pazthor

# Build settings
markdown: kramdown
permalink: pretty

name: El proyecto de blog 
